SET GLOBAL EVENT_SCHEDULER = ON;

DELIMITER //
CREATE EVENT IF NOT EXISTS UPDATE_SUBSCRIPTION_STATUS
 ON SCHEDULE EVERY 1 DAY STARTS CURRENT_DATE + INTERVAL 1 DAY
DO
BEGIN
	UPDATE clients SET clients.has_valid_sub = 0 WHERE DATE(next_payment_at) = CURRENT_DATE;
    INSERT INTO jurnal(client_id, event_id) values (1,9);
END //

DELIMITER ;
