CREATE EVENT IF NOT EXISTS UPDATE_SUBSCRIPTION_STATUS
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_TIMESTAMP
ON COMPLETION PRESERVE
DO
	UPDATE clients SET clients.has_valid_sub = 0 WHERE (TIMESTAMPDIFF(DAY, @subscription_time, NOW()) > 0);